---
- hosts: master
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"


- hosts: workers
  become: yes
 # become_user: tkazymova
  tasks:
    - name: join cluster
      shell: "{{ hostvars['master'].join_command }} --cri-socket unix:///var/run/cri-dockerd.sock"
      args:
        chdir: $HOME
        creates: join_cluster.txt
