version: '3.3'
  services:
    post_db:
      image: mongo:${MONGO_VERSION}
      volumes:
        - post_db:/data/db
      networks:
        backend_net:
          aliases:
            - ${BACKEND_ALIAS}

    ui:
      image: ${USERNAME}/ui:${UI_VERSION}
      volumes:
        - ./ui:/app
      ports:
        - "${UI_PORT}:9292/tcp"
      command: puma --debug -w 2
      networks:
        frontend_net:
          aliases:
            - ${FRONTEND_ALIAS}

    post:
      image: ${USERNAME}/post:${POST_VERSION}
      volumes:
        - ./post-py:/app
      networks:
        frontend_net:
          aliases:
            - ${FRONTEND_ALIAS}
        backend_net:
          aliases:
            - ${BACKEND_ALIAS}

    comment:
      image: ${USERNAME}/comment:${COMMENT_VERSION}
      volumes:
        - ./comment:/app
      networks:
        frontend_net:
          aliases:
            - ${FRONTEND_ALIAS}
        backend_net:
          aliases:
            - ${BACKEND_ALIAS}

  volumes:
    post_db:

  networks:
    frontend_net:
    backend_net:
